### PR TITLE
Add cookie jar to Dialer

### PR DESCRIPTION
**Pull request by SeBBBe**
Add cookie jar to the Dialer so that cookies from a successful QCS login can be passed on. If the jar is not specified, it will be nil and passed onto the gorilla dialer as nil, which is the same as the previous behavior.

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Hi, and thanks for contributing!

Before we can handle your pull request we need you to sign our contributor license agreement.
This is a one-time thing and enables you to contribute without hassle to any of the qlik-oss repositories in the future.

And it only takes a few minutes! Here are some useful links to get you started:

* [Sign the CLA](https://github.com/qlik-oss/open-source/blob/master/sign-cla.md#sign-the-cla)
* [Rationale behind the CLA](https://github.com/qlik-oss/open-source/blob/master/cla-rationale.md)
* [Qlik R&D Open Source repository](https://github.com/qlik-oss/open-source#open-source-at-qlik-rd)
* [Official Slack team](http://branch.qlik.com/slack)

Having troubles? Feel free to reach out to us either here or on Slack!

**Comment by wennmo** [comment]
Thanks for the contribution @SeBBBe! 

Can you add a test case for this in [dialer_test.go](https://github.com/qlik-oss/enigma-go/blob/master/dialer_test.go)?

Otherwise the PR looks good!

**Comment by peol** [comment]
@SeBBBe I've invited you to the qlik-oss organization.

R&D members don't have to sign the CLA.

@wennmo Merge at will :)

**Comment by SeBBBe** [comment]
Alright, added a test case for the proper function of the cookie jar!

**Pull request merged**
