### PR TITLE
Run examples as integration test in Circle CI

### PR DESCRIPTION
**Pull request by wennmo**
This PR adds a step in Circle CI which executes the examples towards a Qlik Analytics Engine running in docker.

Also removed a socket.traffic log that looks accidentally checked in.

### CODE REVIEW

**Comment by wennmo** [comment]
@peol `set -e` in the bash script will trigger an exit if one of the examples are failing.

**Comment by peol** [comment]
@wennmo Ah yeah, but if `go run ...` always exit with 0 it won't exit unless the example crashes. But if we know it's all good, I'm all good :)

**Comment by wennmo** [comment]
@peol I have not verified each of the examples, but I have checked that an example ending up in a Panic will trigger an exit code !=0. It may be that we need to update examples with additional verification steps, but that could be handled in a separate PR imo 🙂

**Comment by peol** [comment]
Sure, go for it :)

**Pull request merged**
